modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="mortysiumsmp"
version="1.7.2"
displayName="MortysiumSMP"
displayURL="https://discord.gg/ssmp"
credits="Mod desenvolvido para MortysiumSMP, criado por 60z/Qnin. Contato em https://discord.gg/ssmp"
authors="60zz"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mortysiumsmp]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
